### ISSUE TITLE
It would be good to support kubectl 

### ISSUE THREAD

**Issue by yaodong-li** [odavid/jenkins-jnlp-slave#14]
I tried to use this image and download kubectl by myself, however, I can't install kubectl. After I download the binary, I faced 'no permission' error when I want to move the downloaded binary to /usr/bin/ folder

**Comment by odavid** [comment]
Hi,
I try to keep the image as thin as possible. You can download the kubectl to ~/bin and add it to the `PATH`. It will do the job.
Hope it helps ...
