### ISSUE TITLE
readme update to prevent docker.sock permission error

### ISSUE THREAD

**Issue by davidhullster** [odavid/jenkins-jnlp-slave#19]
From the readme.md, I understood that adding a volume for the docker socket file to the container as below would allow docker to start within the container. I keep getting permission denied errors accessing the docker.sock.

Is there a step that could be clarified on the readme?

I've tried with both the command line mount and with a Dockerfile.

**Jenkins user is in the docker group**
```
bash-5.1$ egrep docker /etc/group
docker:x:0:jenkins
```

```
% docker run -it -v /var/run/docker.sock:/var/run/docker.sock  odavid-jnlp-slave bash
bash-5.1$ docker run hello-world
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create": dial unix /var/run/docker.sock: connect: permission denied.
```

**Dockerfile**
```
FROM odavid/jenkins-jnlp-slave
VOLUME [ "/var/run/docker.sock" ]
```

**run dockerfile**
```
% docker run -it odavid-jnlp-slave bash
```

**socket permission error**
```
bash-5.1$ docker run hello-world
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create": dial unix /var/run/docker.sock: connect: permission denied.
```

**Comment by odavid** [comment]
I feel it is related to this issue: https://github.com/docker/for-mac/issues/4755

**Comment by davidhullster** [comment]
Excellent! Thanks for the link to that issue, the Internet is filled with docker.sock permission error solutions, I appreciate you finding the one that fits this usecase. I tried, but was unable to reproduce the issue with docker on Ubuntu, it does seem specific to Mac.

I'll test on my mac with the volume mount workaround below, mounting to docker.sock.raw within the container.
https://github.com/docker/for-mac/issues/4755#issuecomment-725498517
`-v /var/run/docker.sock.raw:/var/run/docker.sock `

**Comment by davidhullster** [comment]
thanks for the quick response on this issue, I'l close it now.
