### ISSUE TITLE
Adding Helm into slave

### ISSUE THREAD

**Issue by amd87hh** [odavid/jenkins-jnlp-slave#8]
Hello David,

im already running your Bloody Jenkins on an AWS EKS, which was set up with Ansible & Helm. Until now i have only Maven running on the slave, and im trying to add Helm into it, so i can use Helm in my Jenkinsfile. This is how it looks like:

![values](https://user-images.githubusercontent.com/41955712/60246972-0c5bdb00-98c0-11e9-97cc-2d7ff8ee2928.jpg)

After i added the helm part ive got

/durable-c2e6cd71/script.sh: line 1: helm: not found

Maybe you can help me.

Greetings,

Alexej

**Comment by odavid** [comment]
Hi,
Did you try to use the `container` wrapper?

```
      container('helm') {
        sh """
        helm version
        """
      }
```

I tried it and it worked for me.

**Comment by amd87hh** [comment]
Sorry for the absence, Now i did, and it works. Many thanks! 

Ive already another question and maybe u can help again?

In the Deploy-stage ive first to use helm and kubectl - do i need to open an another container wrapper within the helm container?

**Comment by odavid** [comment]
The container wrapper moves you between each container within the same pod. The workspace is common to all pod's containers. So whenever you need to run helm, you need to wrap it with `container('helm')` and whenever you need maven, you need to switch to `container('maven')`

**Comment by amd87hh** [comment]
Ok Thanks alot
