### ISSUE TITLE
Use Docker 19.03 to access GPUs

### ISSUE THREAD

**Issue by FabianSchurig** [odavid/jenkins-jnlp-slave#9]
Hey there, 

I already used your `jenkins-jnlp-slave` successfully within a docker swarm. That's awesome! But now i want to go a step forward and use it with a container requesting GPU resources.

Docker 19.03 offers a new argument for that
`--gpus all`
see [access-an-nvidia-gpu](https://docs.docker.com/engine/reference/commandline/run/#access-an-nvidia-gpu)

Therefore it would be nice upgrading to the latest docker version and if needed also install [nvidia-docker](https://github.com/NVIDIA/nvidia-docker)

Thank you very much!

Greets Fabi

**Comment by odavid** [comment]
fixed by #10

**Comment by odavid** [comment]
@Bitfroest - 
[v3.29-1-16](https://github.com/odavid/jenkins-jnlp-slave/blob/master/CHANGELOG.md#v329-1-16) released
